// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: answer.proto

// Protobuf Java Version: 3.25.1
package com.thalesgroup.ibis.protos;

public interface AngleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ibis.Angle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float angle = 1;</code>
   * @return The angle.
   */
  float getAngle();

  /**
   * <code>float angle_uncertainty = 2;</code>
   * @return The angleUncertainty.
   */
  float getAngleUncertainty();
}
