// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: answer.proto

// Protobuf Java Version: 3.25.1
package com.thalesgroup.ibis.protos;

public interface AnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ibis.Answer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Identifiant piste (obligatoire)
   * </pre>
   *
   * <code>string track_id = 1;</code>
   * @return The trackId.
   */
  java.lang.String getTrackId();
  /**
   * <pre>
   * Identifiant piste (obligatoire)
   * </pre>
   *
   * <code>string track_id = 1;</code>
   * @return The bytes for trackId.
   */
  com.google.protobuf.ByteString
      getTrackIdBytes();

  /**
   * <pre>
   * Mode ayant obtenu l'information
   * </pre>
   *
   * <code>string source_sensor_mode_id = 2;</code>
   * @return The sourceSensorModeId.
   */
  java.lang.String getSourceSensorModeId();
  /**
   * <pre>
   * Mode ayant obtenu l'information
   * </pre>
   *
   * <code>string source_sensor_mode_id = 2;</code>
   * @return The bytes for sourceSensorModeId.
   */
  com.google.protobuf.ByteString
      getSourceSensorModeIdBytes();

  /**
   * <pre>
   * Horodatage
   * </pre>
   *
   * <code>int64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * Temps nécessaire à l'obtention de l'information
   * </pre>
   *
   * <code>int64 time_taken = 4;</code>
   * @return The timeTaken.
   */
  long getTimeTaken();

  /**
   * <pre>
   * Informations position (optionnel)
   * </pre>
   *
   * <code>.ibis.Angle latitude = 5;</code>
   * @return Whether the latitude field is set.
   */
  boolean hasLatitude();
  /**
   * <pre>
   * Informations position (optionnel)
   * </pre>
   *
   * <code>.ibis.Angle latitude = 5;</code>
   * @return The latitude.
   */
  com.thalesgroup.ibis.protos.Angle getLatitude();
  /**
   * <pre>
   * Informations position (optionnel)
   * </pre>
   *
   * <code>.ibis.Angle latitude = 5;</code>
   */
  com.thalesgroup.ibis.protos.AngleOrBuilder getLatitudeOrBuilder();

  /**
   * <pre>
   * Longitude (rad)
   * </pre>
   *
   * <code>.ibis.Angle longitude = 6;</code>
   * @return Whether the longitude field is set.
   */
  boolean hasLongitude();
  /**
   * <pre>
   * Longitude (rad)
   * </pre>
   *
   * <code>.ibis.Angle longitude = 6;</code>
   * @return The longitude.
   */
  com.thalesgroup.ibis.protos.Angle getLongitude();
  /**
   * <pre>
   * Longitude (rad)
   * </pre>
   *
   * <code>.ibis.Angle longitude = 6;</code>
   */
  com.thalesgroup.ibis.protos.AngleOrBuilder getLongitudeOrBuilder();

  /**
   * <pre>
   * Elevation (m)
   * </pre>
   *
   * <code>.ibis.Distance elevation = 7;</code>
   * @return Whether the elevation field is set.
   */
  boolean hasElevation();
  /**
   * <pre>
   * Elevation (m)
   * </pre>
   *
   * <code>.ibis.Distance elevation = 7;</code>
   * @return The elevation.
   */
  com.thalesgroup.ibis.protos.Distance getElevation();
  /**
   * <pre>
   * Elevation (m)
   * </pre>
   *
   * <code>.ibis.Distance elevation = 7;</code>
   */
  com.thalesgroup.ibis.protos.DistanceOrBuilder getElevationOrBuilder();

  /**
   * <pre>
   * Distance (m)
   * </pre>
   *
   * <code>.ibis.Distance distance = 8;</code>
   * @return Whether the distance field is set.
   */
  boolean hasDistance();
  /**
   * <pre>
   * Distance (m)
   * </pre>
   *
   * <code>.ibis.Distance distance = 8;</code>
   * @return The distance.
   */
  com.thalesgroup.ibis.protos.Distance getDistance();
  /**
   * <pre>
   * Distance (m)
   * </pre>
   *
   * <code>.ibis.Distance distance = 8;</code>
   */
  com.thalesgroup.ibis.protos.DistanceOrBuilder getDistanceOrBuilder();

  /**
   * <pre>
   * Information identification (optionnel)
   * </pre>
   *
   * <code>.ibis.Dimension height = 9;</code>
   * @return Whether the height field is set.
   */
  boolean hasHeight();
  /**
   * <pre>
   * Information identification (optionnel)
   * </pre>
   *
   * <code>.ibis.Dimension height = 9;</code>
   * @return The height.
   */
  com.thalesgroup.ibis.protos.Dimension getHeight();
  /**
   * <pre>
   * Information identification (optionnel)
   * </pre>
   *
   * <code>.ibis.Dimension height = 9;</code>
   */
  com.thalesgroup.ibis.protos.DimensionOrBuilder getHeightOrBuilder();

  /**
   * <pre>
   * Dimension 2 (m)
   * </pre>
   *
   * <code>.ibis.Dimension length = 10;</code>
   * @return Whether the length field is set.
   */
  boolean hasLength();
  /**
   * <pre>
   * Dimension 2 (m)
   * </pre>
   *
   * <code>.ibis.Dimension length = 10;</code>
   * @return The length.
   */
  com.thalesgroup.ibis.protos.Dimension getLength();
  /**
   * <pre>
   * Dimension 2 (m)
   * </pre>
   *
   * <code>.ibis.Dimension length = 10;</code>
   */
  com.thalesgroup.ibis.protos.DimensionOrBuilder getLengthOrBuilder();

  /**
   * <pre>
   * Dimension 3 (m)
   * </pre>
   *
   * <code>.ibis.Dimension width = 11;</code>
   * @return Whether the width field is set.
   */
  boolean hasWidth();
  /**
   * <pre>
   * Dimension 3 (m)
   * </pre>
   *
   * <code>.ibis.Dimension width = 11;</code>
   * @return The width.
   */
  com.thalesgroup.ibis.protos.Dimension getWidth();
  /**
   * <pre>
   * Dimension 3 (m)
   * </pre>
   *
   * <code>.ibis.Dimension width = 11;</code>
   */
  com.thalesgroup.ibis.protos.DimensionOrBuilder getWidthOrBuilder();

  /**
   * <code>.ibis.Velocity velocity = 12;</code>
   * @return Whether the velocity field is set.
   */
  boolean hasVelocity();
  /**
   * <code>.ibis.Velocity velocity = 12;</code>
   * @return The velocity.
   */
  com.thalesgroup.ibis.protos.Velocity getVelocity();
  /**
   * <code>.ibis.Velocity velocity = 12;</code>
   */
  com.thalesgroup.ibis.protos.VelocityOrBuilder getVelocityOrBuilder();

  /**
   * <code>.ibis.RadarCrossSection radarCrossSection = 13;</code>
   * @return Whether the radarCrossSection field is set.
   */
  boolean hasRadarCrossSection();
  /**
   * <code>.ibis.RadarCrossSection radarCrossSection = 13;</code>
   * @return The radarCrossSection.
   */
  com.thalesgroup.ibis.protos.RadarCrossSection getRadarCrossSection();
  /**
   * <code>.ibis.RadarCrossSection radarCrossSection = 13;</code>
   */
  com.thalesgroup.ibis.protos.RadarCrossSectionOrBuilder getRadarCrossSectionOrBuilder();

  /**
   * <pre>
   * Type d'objet, Ex SA
   * </pre>
   *
   * <code>optional string object_type = 14;</code>
   * @return Whether the objectType field is set.
   */
  boolean hasObjectType();
  /**
   * <pre>
   * Type d'objet, Ex SA
   * </pre>
   *
   * <code>optional string object_type = 14;</code>
   * @return The objectType.
   */
  java.lang.String getObjectType();
  /**
   * <pre>
   * Type d'objet, Ex SA
   * </pre>
   *
   * <code>optional string object_type = 14;</code>
   * @return The bytes for objectType.
   */
  com.google.protobuf.ByteString
      getObjectTypeBytes();

  /**
   * <pre>
   * Identification d'objet, Ex SA-11
   * </pre>
   *
   * <code>optional string object_identification = 15;</code>
   * @return Whether the objectIdentification field is set.
   */
  boolean hasObjectIdentification();
  /**
   * <pre>
   * Identification d'objet, Ex SA-11
   * </pre>
   *
   * <code>optional string object_identification = 15;</code>
   * @return The objectIdentification.
   */
  java.lang.String getObjectIdentification();
  /**
   * <pre>
   * Identification d'objet, Ex SA-11
   * </pre>
   *
   * <code>optional string object_identification = 15;</code>
   * @return The bytes for objectIdentification.
   */
  com.google.protobuf.ByteString
      getObjectIdentificationBytes();

  /**
   * <code>optional string waveform_caracterisation = 16;</code>
   * @return Whether the waveformCaracterisation field is set.
   */
  boolean hasWaveformCaracterisation();
  /**
   * <code>optional string waveform_caracterisation = 16;</code>
   * @return The waveformCaracterisation.
   */
  java.lang.String getWaveformCaracterisation();
  /**
   * <code>optional string waveform_caracterisation = 16;</code>
   * @return The bytes for waveformCaracterisation.
   */
  com.google.protobuf.ByteString
      getWaveformCaracterisationBytes();
}
