// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: answer.proto

// Protobuf Java Version: 3.25.1
package com.thalesgroup.ibis.protos;

public interface DimensionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ibis.Dimension)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float dimension = 1;</code>
   * @return The dimension.
   */
  float getDimension();

  /**
   * <code>float dimension_uncertainty = 2;</code>
   * @return The dimensionUncertainty.
   */
  float getDimensionUncertainty();
}
