// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: answer.proto

// Protobuf Java Version: 3.25.1
package com.thalesgroup.ibis.protos;

public interface DistanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ibis.Distance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Distance (m)
   * </pre>
   *
   * <code>float distance = 1;</code>
   * @return The distance.
   */
  float getDistance();

  /**
   * <pre>
   * Incertitude distance
   * </pre>
   *
   * <code>float distance_uncertainty = 2;</code>
   * @return The distanceUncertainty.
   */
  float getDistanceUncertainty();
}
