// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: answer.proto

// Protobuf Java Version: 3.25.1
package com.thalesgroup.ibis.protos;

public interface RadarCrossSectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ibis.RadarCrossSection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float radarCrossSection = 1;</code>
   * @return The radarCrossSection.
   */
  float getRadarCrossSection();

  /**
   * <code>float radarCrossSection_uncertainty = 2;</code>
   * @return The radarCrossSectionUncertainty.
   */
  float getRadarCrossSectionUncertainty();
}
