// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: answer.proto

// Protobuf Java Version: 3.25.1
package com.thalesgroup.ibis.protos;

/**
 * Protobuf type {@code ibis.RadarCrossSection}
 */
public final class RadarCrossSection extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ibis.RadarCrossSection)
    RadarCrossSectionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RadarCrossSection.newBuilder() to construct.
  private RadarCrossSection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RadarCrossSection() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RadarCrossSection();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.thalesgroup.ibis.protos.AnswerOuterClass.internal_static_ibis_RadarCrossSection_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.thalesgroup.ibis.protos.AnswerOuterClass.internal_static_ibis_RadarCrossSection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.thalesgroup.ibis.protos.RadarCrossSection.class, com.thalesgroup.ibis.protos.RadarCrossSection.Builder.class);
  }

  public static final int RADARCROSSSECTION_FIELD_NUMBER = 1;
  private float radarCrossSection_ = 0F;
  /**
   * <code>float radarCrossSection = 1;</code>
   * @return The radarCrossSection.
   */
  @java.lang.Override
  public float getRadarCrossSection() {
    return radarCrossSection_;
  }

  public static final int RADARCROSSSECTION_UNCERTAINTY_FIELD_NUMBER = 2;
  private float radarCrossSectionUncertainty_ = 0F;
  /**
   * <code>float radarCrossSection_uncertainty = 2;</code>
   * @return The radarCrossSectionUncertainty.
   */
  @java.lang.Override
  public float getRadarCrossSectionUncertainty() {
    return radarCrossSectionUncertainty_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Float.floatToRawIntBits(radarCrossSection_) != 0) {
      output.writeFloat(1, radarCrossSection_);
    }
    if (java.lang.Float.floatToRawIntBits(radarCrossSectionUncertainty_) != 0) {
      output.writeFloat(2, radarCrossSectionUncertainty_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Float.floatToRawIntBits(radarCrossSection_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, radarCrossSection_);
    }
    if (java.lang.Float.floatToRawIntBits(radarCrossSectionUncertainty_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, radarCrossSectionUncertainty_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.thalesgroup.ibis.protos.RadarCrossSection)) {
      return super.equals(obj);
    }
    com.thalesgroup.ibis.protos.RadarCrossSection other = (com.thalesgroup.ibis.protos.RadarCrossSection) obj;

    if (java.lang.Float.floatToIntBits(getRadarCrossSection())
        != java.lang.Float.floatToIntBits(
            other.getRadarCrossSection())) return false;
    if (java.lang.Float.floatToIntBits(getRadarCrossSectionUncertainty())
        != java.lang.Float.floatToIntBits(
            other.getRadarCrossSectionUncertainty())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RADARCROSSSECTION_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getRadarCrossSection());
    hash = (37 * hash) + RADARCROSSSECTION_UNCERTAINTY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getRadarCrossSectionUncertainty());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.thalesgroup.ibis.protos.RadarCrossSection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thalesgroup.ibis.protos.RadarCrossSection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thalesgroup.ibis.protos.RadarCrossSection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thalesgroup.ibis.protos.RadarCrossSection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thalesgroup.ibis.protos.RadarCrossSection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thalesgroup.ibis.protos.RadarCrossSection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thalesgroup.ibis.protos.RadarCrossSection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thalesgroup.ibis.protos.RadarCrossSection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.thalesgroup.ibis.protos.RadarCrossSection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.thalesgroup.ibis.protos.RadarCrossSection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thalesgroup.ibis.protos.RadarCrossSection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thalesgroup.ibis.protos.RadarCrossSection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.thalesgroup.ibis.protos.RadarCrossSection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ibis.RadarCrossSection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ibis.RadarCrossSection)
      com.thalesgroup.ibis.protos.RadarCrossSectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thalesgroup.ibis.protos.AnswerOuterClass.internal_static_ibis_RadarCrossSection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thalesgroup.ibis.protos.AnswerOuterClass.internal_static_ibis_RadarCrossSection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thalesgroup.ibis.protos.RadarCrossSection.class, com.thalesgroup.ibis.protos.RadarCrossSection.Builder.class);
    }

    // Construct using com.thalesgroup.ibis.protos.RadarCrossSection.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      radarCrossSection_ = 0F;
      radarCrossSectionUncertainty_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.thalesgroup.ibis.protos.AnswerOuterClass.internal_static_ibis_RadarCrossSection_descriptor;
    }

    @java.lang.Override
    public com.thalesgroup.ibis.protos.RadarCrossSection getDefaultInstanceForType() {
      return com.thalesgroup.ibis.protos.RadarCrossSection.getDefaultInstance();
    }

    @java.lang.Override
    public com.thalesgroup.ibis.protos.RadarCrossSection build() {
      com.thalesgroup.ibis.protos.RadarCrossSection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.thalesgroup.ibis.protos.RadarCrossSection buildPartial() {
      com.thalesgroup.ibis.protos.RadarCrossSection result = new com.thalesgroup.ibis.protos.RadarCrossSection(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.thalesgroup.ibis.protos.RadarCrossSection result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.radarCrossSection_ = radarCrossSection_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.radarCrossSectionUncertainty_ = radarCrossSectionUncertainty_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.thalesgroup.ibis.protos.RadarCrossSection) {
        return mergeFrom((com.thalesgroup.ibis.protos.RadarCrossSection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.thalesgroup.ibis.protos.RadarCrossSection other) {
      if (other == com.thalesgroup.ibis.protos.RadarCrossSection.getDefaultInstance()) return this;
      if (other.getRadarCrossSection() != 0F) {
        setRadarCrossSection(other.getRadarCrossSection());
      }
      if (other.getRadarCrossSectionUncertainty() != 0F) {
        setRadarCrossSectionUncertainty(other.getRadarCrossSectionUncertainty());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              radarCrossSection_ = input.readFloat();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 21: {
              radarCrossSectionUncertainty_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private float radarCrossSection_ ;
    /**
     * <code>float radarCrossSection = 1;</code>
     * @return The radarCrossSection.
     */
    @java.lang.Override
    public float getRadarCrossSection() {
      return radarCrossSection_;
    }
    /**
     * <code>float radarCrossSection = 1;</code>
     * @param value The radarCrossSection to set.
     * @return This builder for chaining.
     */
    public Builder setRadarCrossSection(float value) {

      radarCrossSection_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>float radarCrossSection = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRadarCrossSection() {
      bitField0_ = (bitField0_ & ~0x00000001);
      radarCrossSection_ = 0F;
      onChanged();
      return this;
    }

    private float radarCrossSectionUncertainty_ ;
    /**
     * <code>float radarCrossSection_uncertainty = 2;</code>
     * @return The radarCrossSectionUncertainty.
     */
    @java.lang.Override
    public float getRadarCrossSectionUncertainty() {
      return radarCrossSectionUncertainty_;
    }
    /**
     * <code>float radarCrossSection_uncertainty = 2;</code>
     * @param value The radarCrossSectionUncertainty to set.
     * @return This builder for chaining.
     */
    public Builder setRadarCrossSectionUncertainty(float value) {

      radarCrossSectionUncertainty_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float radarCrossSection_uncertainty = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRadarCrossSectionUncertainty() {
      bitField0_ = (bitField0_ & ~0x00000002);
      radarCrossSectionUncertainty_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ibis.RadarCrossSection)
  }

  // @@protoc_insertion_point(class_scope:ibis.RadarCrossSection)
  private static final com.thalesgroup.ibis.protos.RadarCrossSection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.thalesgroup.ibis.protos.RadarCrossSection();
  }

  public static com.thalesgroup.ibis.protos.RadarCrossSection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RadarCrossSection>
      PARSER = new com.google.protobuf.AbstractParser<RadarCrossSection>() {
    @java.lang.Override
    public RadarCrossSection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RadarCrossSection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RadarCrossSection> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.thalesgroup.ibis.protos.RadarCrossSection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

