// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

// Protobuf Java Version: 3.25.1
package com.thalesgroup.ibis.protos;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ibis.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Identifiants des modes capteurs
   * </pre>
   *
   * <code>repeated string sensor_mode_ids = 1;</code>
   * @return A list containing the sensorModeIds.
   */
  java.util.List<java.lang.String>
      getSensorModeIdsList();
  /**
   * <pre>
   * Identifiants des modes capteurs
   * </pre>
   *
   * <code>repeated string sensor_mode_ids = 1;</code>
   * @return The count of sensorModeIds.
   */
  int getSensorModeIdsCount();
  /**
   * <pre>
   * Identifiants des modes capteurs
   * </pre>
   *
   * <code>repeated string sensor_mode_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The sensorModeIds at the given index.
   */
  java.lang.String getSensorModeIds(int index);
  /**
   * <pre>
   * Identifiants des modes capteurs
   * </pre>
   *
   * <code>repeated string sensor_mode_ids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the sensorModeIds at the given index.
   */
  com.google.protobuf.ByteString
      getSensorModeIdsBytes(int index);

  /**
   * <pre>
   * identifiant de la piste
   * </pre>
   *
   * <code>string track_id = 2;</code>
   * @return The trackId.
   */
  java.lang.String getTrackId();
  /**
   * <pre>
   * identifiant de la piste
   * </pre>
   *
   * <code>string track_id = 2;</code>
   * @return The bytes for trackId.
   */
  com.google.protobuf.ByteString
      getTrackIdBytes();

  /**
   * <pre>
   * Distance à la plateforme
   * </pre>
   *
   * <code>int64 distance = 3;</code>
   * @return The distance.
   */
  long getDistance();
}
