// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: answer.proto

// Protobuf Java Version: 3.25.1
package com.thalesgroup.ibis.protos;

public interface VelocityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ibis.Velocity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Vitesse de la piste 
   * </pre>
   *
   * <code>float velocity = 1;</code>
   * @return The velocity.
   */
  float getVelocity();

  /**
   * <pre>
   * Incertitude vitesse
   * </pre>
   *
   * <code>float velocity_uncertainty = 2;</code>
   * @return The velocityUncertainty.
   */
  float getVelocityUncertainty();
}
